name: ar_unib
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0
  flutter_secure_storage: ^9.2.4
  camera: ^0.11.2
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  uuid: ^4.5.1
  flutter_dotenv: ^6.0.0
  image_picker: ^1.2.0
  cloudinary_flutter: ^1.3.0
  cloudinary_url_gen: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg